apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  annotations:
    source-file: podinfoapp1-Kustomization-resource.yaml
  name: podinfoapp1
  namespace: podinfo
spec:
  interval: 5m0s
  path: ./kustomize
  prune: false
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: podinfosourceone
    namespace: flux-system
  targetNamespace: podinfo
  timeout: 3m0s
  wait: true
