apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  annotations:
    source-file: cap1-Kustomization-resource.yaml
  name: cap1
  namespace: capacitor
spec:
  interval: 5m0s
  prune: false
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: capgitsource
    namespace: capacitor
  targetNamespace: capacitor
  timeout: 3m0s
  wait: true
