apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  annotations:
    source-file: fluxsysapp1-Kustomization-resource.yaml
  name: fluxsysapp1
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./kustomize
  prune: false
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: fluxsourcepne
    namespace: flux-system
  targetNamespace: flux-system
  timeout: 3m0s
  wait: true
