apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  annotations:
    source-file: fluxsourcepne-GitRepository-resource.yaml
  name: fluxsourcepne
  namespace: flux-system
spec:
  interval: 2m0s
  ref:
    branch: master
  url: https://github.com/stefanprodan/podinfo
