apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  annotations:
    source-file: fluxapp2-Kustomization-resource.yaml
  name: fluxapp2
  namespace: podinfo
spec:
  interval: 5m0s
  prune: false
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: fluxapp2
    namespace: podinfo
  targetNamespace: podinfo
  timeout: 3m0s
  wait: true
